"""empty message

Revision ID: 51e750fc9351
Revises: 7fafa1d59f58
Create Date: 2023-10-23 21:28:54.584659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e750fc9351'
down_revision: Union[str, None] = '7fafa1d59f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('rating', sa.Integer(), server_default=sa.text('100'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'rating')
    # ### end Alembic commands ###
