"""empty message

Revision ID: f98ecfae91cf
Revises: 921bace40937
Create Date: 2023-09-29 16:23:38.562595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98ecfae91cf'
down_revision: Union[str, None] = '921bace40937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('base', sa.String(), nullable=True),
    sa.Column('left_side', sa.String(), nullable=True),
    sa.Column('right_side', sa.String(), nullable=True),
    sa.Column('game_style', sa.Boolean(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
