"""empty message

Revision ID: 7168fb90fe56
Revises: 1b30385a1893
Create Date: 2023-10-01 15:02:40.623472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7168fb90fe56'
down_revision: Union[str, None] = '1b30385a1893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('first_player_score', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('second_player_score', sa.Integer(), nullable=False))
    op.drop_column('games', 'first_pl_score')
    op.drop_column('games', 'second_pl_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('second_pl_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('first_pl_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('games', 'second_player_score')
    op.drop_column('games', 'first_player_score')
    # ### end Alembic commands ###
