"""empty message

Revision ID: 4c73e82c16a9
Revises: e8e488fa0ff6
Create Date: 2023-09-28 10:34:44.395574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c73e82c16a9'
down_revision: Union[str, None] = 'e8e488fa0ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(), nullable=False))
    op.drop_column('users', 'second_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
