"""empty message

Revision ID: 9e726c0d5865
Revises: c2fad429e356
Create Date: 2023-10-02 14:02:10.254152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e726c0d5865'
down_revision: Union[str, None] = 'c2fad429e356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('tournament_type', sa.Enum('standard', 'extend', native_enum=False), nullable=False),
    sa.Column('tournament_date', sa.Date(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments')
    # ### end Alembic commands ###
