"""empty message

Revision ID: 7fafa1d59f58
Revises: ca87723290d1
Create Date: 2023-10-23 21:28:16.625589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fafa1d59f58'
down_revision: Union[str, None] = 'ca87723290d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
