"""empty message

Revision ID: da9a33982efe
Revises: 589ca41e9636
Create Date: 2023-10-24 19:44:06.999061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9a33982efe'
down_revision: Union[str, None] = '589ca41e9636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
