"""empty message

Revision ID: fbe6dd1d32f3
Revises: da9a33982efe
Create Date: 2023-10-24 20:54:08.858409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe6dd1d32f3'
down_revision: Union[str, None] = 'da9a33982efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('loser_score', sa.Integer(), nullable=False))
    op.drop_column('games', 'second_player_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('second_player_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('games', 'loser_score')
    # ### end Alembic commands ###
