"""empty message

Revision ID: 589ca41e9636
Revises: 382ec947f3ca
Create Date: 2023-10-24 19:11:55.138747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589ca41e9636'
down_revision: Union[str, None] = '382ec947f3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'game_style',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('profiles', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.alter_column('profiles', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'game_style',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
