"""empty message

Revision ID: 382ec947f3ca
Revises: 51e750fc9351
Create Date: 2023-10-23 23:56:01.774904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382ec947f3ca'
down_revision: Union[str, None] = '51e750fc9351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('loser_id', sa.Uuid(), nullable=False))
    op.add_column('games', sa.Column('winner_score', sa.Integer(), nullable=False))
    op.drop_constraint('games_second_player_id_fkey', 'games', type_='foreignkey')
    op.drop_constraint('games_first_player_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['loser_id'], ['id'])
    op.drop_column('games', 'first_player_score')
    op.drop_column('games', 'second_player_id')
    op.drop_column('games', 'first_player_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('first_player_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('second_player_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('first_player_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_first_player_id_fkey', 'games', 'users', ['first_player_id'], ['id'])
    op.create_foreign_key('games_second_player_id_fkey', 'games', 'users', ['second_player_id'], ['id'])
    op.drop_column('games', 'winner_score')
    op.drop_column('games', 'loser_id')
    # ### end Alembic commands ###
