"""empty message

Revision ID: 1b30385a1893
Revises: 3dab8c02a7e5
Create Date: 2023-09-29 16:27:24.332306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b30385a1893'
down_revision: Union[str, None] = '3dab8c02a7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('profiles', sa.Column('city', sa.String(), nullable=False))
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'city')
    op.drop_column('profiles', 'date_of_birth')
    # ### end Alembic commands ###
